name: publish

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use Node.js 14
        uses: actions/setup-node@v1
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 14

      - name: npm install and publish
        run: |
          npm install
          npm run test

        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
